/* Auto-generated by genmsg_cpp for file /home/aaroncz/fuerte_workspace/AR.Drone.2.0/image_process/msg/Positions.msg */
#ifndef IMAGE_PROCESS_MESSAGE_POSITIONS_H
#define IMAGE_PROCESS_MESSAGE_POSITIONS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace image_process
{
template <class ContainerAllocator>
struct Positions_ {
  typedef Positions_<ContainerAllocator> Type;

  Positions_()
  : posX(0)
  , posY(0)
  {
  }

  Positions_(const ContainerAllocator& _alloc)
  : posX(0)
  , posY(0)
  {
  }

  typedef int16_t _posX_type;
  int16_t posX;

  typedef int16_t _posY_type;
  int16_t posY;


  typedef boost::shared_ptr< ::image_process::Positions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_process::Positions_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Positions
typedef  ::image_process::Positions_<std::allocator<void> > Positions;

typedef boost::shared_ptr< ::image_process::Positions> PositionsPtr;
typedef boost::shared_ptr< ::image_process::Positions const> PositionsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::image_process::Positions_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::image_process::Positions_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace image_process

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::image_process::Positions_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::image_process::Positions_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::image_process::Positions_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d45eb622e055a6c42c62b2012431a993";
  }

  static const char* value(const  ::image_process::Positions_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd45eb622e055a6c4ULL;
  static const uint64_t static_value2 = 0x2c62b2012431a993ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_process::Positions_<ContainerAllocator> > {
  static const char* value() 
  {
    return "image_process/Positions";
  }

  static const char* value(const  ::image_process::Positions_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::image_process::Positions_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 posX\n\
int16 posY\n\
\n\
";
  }

  static const char* value(const  ::image_process::Positions_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::image_process::Positions_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::image_process::Positions_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.posX);
    stream.next(m.posY);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Positions_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_process::Positions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::image_process::Positions_<ContainerAllocator> & v) 
  {
    s << indent << "posX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.posY);
  }
};


} // namespace message_operations
} // namespace ros

#endif // IMAGE_PROCESS_MESSAGE_POSITIONS_H

